### ISSUE TITLE
Version 1.11.1 is not found

### ISSUE THREAD

**Issue by icharge** [highsource/jaxb2-basics#109]
![image](https://user-images.githubusercontent.com/1619007/62680166-ca56a680-b9e0-11e9-8b0b-9a05b133e6c0.png)

**Comment by highsource** [comment]
1.11.1 was published by mistake.

https://mvnrepository.com/artifact/org.jvnet.jaxb2_commons/jaxb2-basics/1.11.1-PUBLISHED-BY-MISTAKE

Please use 0.11.1 oder 0.12.0.
