### ISSUE TITLE
Update activation dep to jakarata jar

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb2-basics#125]

**Comment by sebersole** [comment]
https://github.com/highsource/jaxb2-basics/pull/129 should address this

**Comment by AB006KF** [comment]
When will this be published? I really need JAXB 3 support for this plugin.

Thanks

**Comment by sebersole** [comment]
FWIW, I just used a patched version - https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics

It is only a build time dep for us, so this was fine.  But I think this is only ever used at build time, so maybe that would work for you as well

**Comment by coderrock2021** [comment]
Hi @sebersole , 

I am facing the same issue and am hoping to have an official released jaxb2_basics JAR on the maven central repo that has the above fix for Jakarta & JAXB 3 support for the plugin.

The link for the patched version that you mentioned in the above comment does not exist. [ https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics]


Could you please suggest an alternative where I can get the jaxb2_basics dependency

**Comment by coderrock2021** [comment]
> FWIW, I just used a patched version - https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics
> 
> It is only a build time dep for us, so this was fine. But I think this is only ever used at build time, so maybe that would work for you as well

Hi @sebersole ,

I am facing the same issue and am hoping to have an official released jaxb2_basics JAR on the maven central repo that has the above fix for Jakarta & JAXB 3 support for the plugin.

The link for the patched version that you mentioned in the above comment does not exist. [ https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics]

Could you please suggest an alternative where I can get the jaxb2_basics dependency

**Comment by sebersole** [comment]
I have no affiliation with Jakarta nor JAXB.  We simply use JAXB in my project.  I gave you the rundown on what I did.  

Carry on

**Comment by sebersole** [comment]
> The link for the patched version that you mentioned in the above comment does not exist. [ https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics]

https://github.com/hibernate/hibernate-orm/tree/main/patched-libs/jaxb2-basics

**Comment by coderrock2021** [comment]
> > The link for the patched version that you mentioned in the above comment does not exist. [ https://github.com/hibernate/hibernate-orm/tree/wip/6.0/patched-libs/jaxb2-basics]
> 
> https://github.com/hibernate/hibernate-orm/tree/main/patched-libs/jaxb2-basics

Thank you @sebersole . I'll give it a try.

**Comment by mattrpav** [comment]
I've messaged @highsource to see if he still has plans to do additional releases. If he has moved on, I'd be happy to carry the changes forward with new releases to Maven Central.

**Comment by coderrock2021** [comment]
That would be great. Thank you !

**Comment by fbraun4358** [comment]
> I've messaged @highsource to see if he still has plans to do additional releases. If he has moved on, I'd be happy to carry the changes forward with new releases to Maven Central.

I think he died in January of 2021. If you find his [twitter](https://twitter.com/orless?lang=en) (same profile pic and same name, and looks to be a software guy) you can see some photos of him in the hospital.

You can also find an obituary site for an [Alexey Valikov](https://good-bye.org/alexey-valikov/) which looks very much like him and has all the same interests.

I have been putting off migrating past java 8 at my current job because of lack of jakarta support in this.

How are you running your generation? Are you using one of the maven plugins? Either highsource's or the apache one? Neither looks to have good jaxb3 support if at all. Or are you using the plugin via a command line generation?

If you are willing to take over the some of the maintenance that would be great. Let me know if you would like some help. It might be worth it to invest some time in cleaning up any fork to just focus on Jakarta and jaxb3 and I have this weird fascination for cleaning up projects.

**Comment by Nutstree** [comment]
> I've messaged @highsource to see if he still has plans to do additional releases. If he has moved on, I'd be happy to carry the changes forward with new releases to Maven Central.

+1 if the project would be continued

**Comment by mattrpav** [comment]
Please see: https://github.com/highsource/maven-jaxb2-plugin/issues/206

**Comment by Vampire** [comment]
@mattrpav so will you also carry on this one?
Especially the mentioned PR for Jakarta support?

**Comment by laurentschoelens** [comment]
We are currently working with @mattrpav on consolidating all jaxb related tools in highsource/jaxb-tools repo.
Missing hyperjaxb but 2.0.4 released version contains already jaxb2-basics with new groupId
3.0.0 will follow soon with jaxb3 support and shortly after 4.0.0 for jaxb4 and jdk11 baseline.

**Comment by laurentschoelens** [comment]
Fixed in https://github.com/highsource/jaxb-tools/commit/dcbc397344c1bd2954c87572045a1590dbfe9607
Published under jaxb-tools v3
