### ISSUE TITLE
Jakarta classes support for jaxb2-basics

### ISSUE THREAD

**Issue by yurii20041** [highsource/jaxb2-basics#162]
Hi,
jaxb2-basics isn't compatible with Jakarta EE 9 classes provided by Spring 6.
E.g. JAXBEqualsStrategy uses javax.xml.bind.JAXBElement inside the logic that isn't compatible with the latest Spring version.

I'm wondering, if you have any plan to fix it?
Thanks!

**Comment by patrodyne** [comment]
My fork at [hisrc-basicjaxb](https://github.com/patrodyne/hisrc-basicjaxb) replaces the `javax.xml.bind` imports with their newer `jakarta.xml.bind` equivalents. My fork's [releases](https://repo1.maven.org/maven2/org/patrodyne/jvnet/) starting with v2.0.0 in the Maven Central Repository support the _Jakarta EE XML Binding, Specification v3.0._

**Note:** If you are interested then be sure to review that project's [readme](https://github.com/patrodyne/hisrc-basicjaxb#readme) for changes to package names and namespaces. If you have questions about my fork, please post any questions over there.

**Comment by yurii20041** [comment]
Hi @patrodyne,
Unfortunately, I can't find the mentioned 2.0.0 version for hisrc-basicjaxb in the maven central repo:
https://repo1.maven.org/maven2/org/patrodyne/jvnet/hisrc-basicjaxb/

I'm looking forward to your clarification.
Thanks!

**Comment by patrodyne** [comment]
No problem, see [Clarification of hisrc-basicjaxb-plugins](https://github.com/patrodyne/hisrc-basicjaxb/issues/2).

**Comment by proclos** [comment]
I just used this fork of your project with JAXB version 4.0.2 (Jakarta): 
https://github.com/qantasloyalty/lsl-jaxb3-basics

Though is claims only version 3 support, it seems to work also for version 4 already. 
I tried it out in the scope of quarkus3, Alpha5.

Maybe you can/want to reintegrate this fork?

**Comment by laurentschoelens** [comment]
@proclos : thanks for your comment. I think that people should have done PR with their forks (I've seen many forks from the original @highsource work from both jaxb-basics and jaxb-plugin).

Since jaxb 3 and jaxb 4 are not so different (jaxb 4 has jdk11 baseline), the artefact should just work for both.

@mattrpav  will soon migrate both jaxb2-basics and plugin to jakarta jaxb support I think

**Comment by linuxmin** [comment]
Any updates on this? @laurentschoelens @mattrpav

**Comment by laurentschoelens** [comment]
Hi @linuxmin : sorry but I just provided the PR, I'm not official contributor in highsource projects.
@mattrpav : If I can help on this, or do some rework, just tell me, I'd be glad to help more on this migrations.

**Comment by mattrpav** [comment]
Hey @laurentschoelens @linuxmin - hoping to get to this shortly. We need it with ActiveMQ as well. I have been tied up getting jakarta work going over there as well. Thanks for the patience. For sure, we'll get this going.

Questions:

1. I think we should cleanup the package names (remove version # and _). Does anyone see any issues with package names changing? My thinking is that these classes get added in via generation and aren't used directly. Also, the previous classes had jaxb2 in the name so that would justify supporting a change imo. Thoughts?

2. Along those lines, going to see about tidying up the maven gav to org.jvnet.jaxb (no vers number in the groupId). If we need multi-version we can handle that in the artifactId. Any issues?

Thanks!
Matt

**Comment by laurentschoelens** [comment]
> Hey @laurentschoelens @linuxmin - hoping to get to this shortly. We need it with ActiveMQ as well. I have been tied up getting jakarta work going over there as well. Thanks for the patience. For sure, we'll get this going.
> 
> Questions:
> 
> 1. I think we should cleanup the package names (remove version # and _). Does anyone see any issues with package names changing? My thinking is that these classes get added in via generation and aren't used directly. Also, the previous classes had jaxb2 in the name so that would justify supporting a change imo. Thoughts?
That what I made by changing package name to jaxb3_basics. If you want me to do the refacto to jaxbbasics package name, tell me, I can rework on this

> 2. Along those lines, going to see about tidying up the maven gav to org.jvnet.jaxb (no vers number in the groupId). If we need multi-version we can handle that in the artifactId. Any issues?
No issues on this too.

> 
> Thanks! Matt

**Comment by timomeinen** [comment]
Any news on the planned migration plan?

In the meanwhile I am using `hisrc-basicjaxb-plugins` from @patrodyne and it works nicely.

**Comment by laurentschoelens** [comment]
Hi @timomeinen : work is still in progress
Hope to get well soon.

**Comment by marinkobabic** [comment]
Hi @laurentschoelens @mattrpav what is the actual state here? Should we wait for the new version or look for an alternate solution?

**Comment by laurentschoelens** [comment]
Hi @marinkobabic 
We merged jaxb2-basics in main repo jaxb-tools (which is former maven-jaxb2-plugin).
We're working on bugfixes on v2.3 version of jaxb and then move on to provide the first version of v3 jaxb jakarta version

If you need jakarta support before official release, see this comment which propose a quickwin by replacing javax package import by jakarta ones after generation : https://github.com/highsource/jaxb-tools/issues/233#issuecomment-1632508716

Tested OK and jaxb-basics-runtime doesn't have jaxb 2.3 dependencies in my opinion so it's OK.

**Comment by laurentschoelens** [comment]
@marinkobabic we did release v2 / v3 / v4 versions of jaxb-tools recently with jakarta support

**Comment by laurentschoelens** [comment]
Fixed in https://github.com/highsource/jaxb-tools/releases/tag/3.0.0 and https://github.com/highsource/jaxb-tools/releases/tag/4.0.0

**Comment by david0** [comment]
Great that a way has been found to continue Alexeys legacy!!!
