### ISSUE TITLE
Is there any plan to upgrade javaparser

### ISSUE THREAD

**Issue by rahogata** [highsource/jaxb2-basics#172]
Hi, 
One of my company's security analysis engines report javaparser as dual lgpl and gpl for the javaparser 1.0.11. Latest javaparser now available in lgpl or apache license. Is there any plan to upgrade javaparser?

**Comment by laurentschoelens** [comment]
Hi @rahogata 

Do you need upgrade for jaxb2 or jaxb4 ?

Javaparser v3 upgrade has been adressed here : https://github.com/highsource/jaxb-tools/issues/529

It's already available in jaxb-tools v4.0.6+

It's also backportes in next v2 release which should happen soon

**Comment by rahogata** [comment]
Thanks, I will upgrade to jaxb4.

**Comment by laurentschoelens** [comment]
If you still need jaxb2 support, it'll be available in next v2 release

**Comment by laurentschoelens** [comment]
You can use 2.0.12 for jaxb 2.3 support which has been migrated to javaparser 3 too
