### ISSUE TITLE
Pluralize names of simplified-out lists

### ISSUE THREAD

**Issue by borismarin** [highsource/jaxb2-basics#18]
The simplify plugin generates
```java
protected List<FooType> foo; // foo is singular
protected List<BarType> far; // bar is singular
```
from the complex property
```xml
<xs:choice maxOccurs="unbounded">
    <xs:element name="foo" type="FooType"/>
    <xs:element name="far" type="BarType"/>
</xs:choice>
```
Would it be possible to generate "pluralized" lists (similarly to what [simpler&better binding mode](https://jaxb.java.net/2.1.2/docs/vendorCustomizations.html#simple) does), i.e.

```java
protected List<FooType> foos; // Notice fooS instead of Foo
protected List<BarType> bars;  // Notice barS instead of Bar
```
?

**Comment by highsource** [comment]
Sure.

But I'll also have to add an option to disable plural form to allow backwards compatibility.

**Comment by highsource** [comment]
Implemented, but must be documented:

https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin

**Comment by borismarin** [comment]
Wow, that was fast! Wouldn't it be better to default to singular, and trigger plurals by using the flag?

**Comment by highsource** [comment]
I also thought about it.
The question is usability for future users vs. backwards compatibility for existing users.
I think you're right. Backwards compatibility is more important.
I'll make `usePluralForm` `false` by default.

**Comment by borismarin** [comment]
I have added a section on options/pluralization to [the docs](https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin). Once you decide on how to enable/disable pluralization, it must be updated accordingly.

**Comment by highsource** [comment]
I think it's better to disable the pluralization by default.
Implemented now.

Documentation:

* https://github.com/highsource/jaxb2-basics/wiki/JAXB2-Simplify-Plugin#pluralization

Would it be OK to credit you in the release notes?

* https://github.com/highsource/jaxb2-basics/releases/tag/untagged-a1058ebc36505be28b5c

Thank you very much for your contribution!

**Comment by borismarin** [comment]
No worries, you are the one who did all the hard work...
I've made a small change to the code snippets on the docs (the 'children'
list and the type for 'foot' where missing).

Thanks!

**Comment by borismarin** [comment]
@highsource any idea when 0.9.3 will make it to the mvn repo?

**Comment by highsource** [comment]
@borismarin It is released now, should appear in the central within an hour.

**Comment by borismarin** [comment]
Great!
