### ISSUE TITLE
usage JAXB2 Basics Plugins

### ISSUE THREAD

**Issue by mistersound** [highsource/jaxb2-basics#28]
Hello,

How to install and use Simplify Plugin on eclipse?
I am getting "[ERROR] Unsupported binding namespace "http://jaxb2-commons.dev.java.net/basic/simplify". Perhaps you meant "http://jaxb.dev.java.net/plugin/code-injector"?"
and don't know how to install stuff to make it works.

Thanks

**Comment by highsource** [comment]
Sorry, I can't consult you on how to use XJC plugins in your target IDE. I think you should generate code using build scripts and not via IDE directly.

Please address this question to the authors of the JAXB Eclipse plugin: how to use XJC plugins for code generation?
