### ISSUE TITLE
 toString plugin not taking it -XtoString-toStringStrategyClass custom strategy class

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-basics#57]
http://jira.highsource.org/browse/JIIB-51

**Comment by AntonSaburov** [comment]
It works so (I had to enter TWO strings):
<arg>-XtoString</arg>
<arg>-XtoString-toStringStrategyClass=org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy</arg>

**Comment by highsource** [comment]
This is by design. One option is to turn on the plugin, the other to provide configuration.
You still need `-XtoString` in any case.

**Comment by AntonSaburov** [comment]
Thank you. But documentation is not clear. I spent much time to find out solution

**Comment by highsource** [comment]
Added documentation:
https://github.com/highsource/jaxb2-basics/wiki/JAXB2-ToString-Plugin

**Comment by cstenkes** [comment]
It would be nice to fix this issues regarding to generate override on the mentioned methods, otherwise the generated code is full of warning. In my case after generating 1854 warnings occurred  in the code which is not really nice, and break on the QA filters of the projects.
