### ISSUE TITLE
Add @Overrride to equals(Object), hashCode(), toString()

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-basics#60]
http://jira.highsource.org/browse/JIIB-33

**Comment by adherr** [comment]
Any news on this lately? I'd use it if it existed, because of our group's coding standards and subsequent compiler settings.

Also, I think the reason I didn't find this issue quickly is the extra r in @Overrride

**Comment by highsource** [comment]
Hi,

to be honest I didn't have a hight prio on that. I'd appreciate a PR with the fix.

Best wishes,
Alexey
