### ISSUE TITLE
CamelCase Always plugin

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-basics#61]
http://jira.highsource.org/browse/JIIB-25

**Comment by rbertucat** [comment]
I'm trying to migrate from jaxb2 to jaxb4. The CamelCase Always plugin was working pretty well.
`com.sun.xml.bind.api.impl.NameConverter` is now `org.glassfish.jaxb.core.api.impl.NameConverter` so the plugin now fails.

Any chance you could suggest a workaround - a plugin doing the same end result or any chance the CamelCase Always plugin would be updated?

Thanks

**Comment by rbertucat** [comment]
Hi @laurentschoelens,
I've created the issue here: https://github.com/highsource/jaxb-tools/issues/460
Thanks!

**Comment by laurentschoelens** [comment]
Thanks for the new issue.
When treated, both could be closed.
Hope the migration guide could also help you
