### ISSUE TITLE
DefaultHashCodeStrategy.hashCode does not compute a hashCode for modified object

### ISSUE THREAD

**Issue by halfdan87** [highsource/jaxb2-basics#67]
@Override
	public int hashCode(ObjectLocator locator, int hashCode, Object value,
			boolean valueSet) {
		return valueSet ? (hashCode * iConstant + 1) : hashCode(locator,
				hashCode * iConstant, value);
	}

Is this code correct? If the value was changed (valueSet == true) than we skip hashCode calculation.
It is opposite to the DefaultEqualsStrategy's equals methods behavior.

**Comment by highsource** [comment]
Indeed. A major bug, I wonder how it went undetected for so long.

**Comment by adischerrer** [comment]
The latest release 0.11 still contains this bug (#67). Are you going to create a new version containing this fix?

**Comment by highsource** [comment]
Does the latest snapshot work for you?

**Comment by adischerrer** [comment]
Just created a 0.11.1-SNAPSHOT from master and... YES, it works as expected.
Could you please create an official 0.11.1 please?

**Comment by highsource** [comment]
Will do. Thank you for confirmation.

**Comment by highsource** [comment]
Released.

**Comment by adischerrer** [comment]
Great. Thank you.
Is the new release number 1.11.1 by design or should it rather be 0.11.1 ?

**Comment by highsource** [comment]
Oh. :( 0.11.1 My Bad.

**Comment by highsource** [comment]
0.11.1 released now. 1.11.1 is marked as `PUBLISHED-BY-MISTAKE`.
