### ISSUE TITLE
Restore backwards compatibility with 0.10.0 and prior releases

### ISSUE THREAD

**Issue by rhstone** [highsource/jaxb2-basics#74]
With the addition of the new EqualsStrategy2 (and HashCode, Copy, ToString and Merge) interfaces in 0.11.0, the return type of the public static INSTANCE variable in org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy (and others) was changed from `FunctionStrategy` to `JAXBFunctionStrategy`. I understand this was done because an additional interface, `FunctionStrategy2`, was added in numerous places. 

Unfortunately, Java does not allow for assignment conversion of directly accessed fields in the same manner as a method. For example, if the method return signature changed from an interface to a concrete class, the JVM would handle the assignment back to a variable type declared with the interface. In this instance the generated code is directly accessing a field, INSTANCE, whose return type changed between 0.10.0 and 0.11.0. That means my large library of generated code (much of it at stable, released versions), cannot simultaneously coexist with newly developed code with the 0.11.0 version of the jaxb2-basics-runtime.

One possible way to do this is to substitute the following:

```
/* This is one example of the newly implemented JAXBEqualsStrategy code */
public static JAXBEqualsStrategy INSTANCE = new JAXBEqualsStrategy();
```

with 

```
/* Define INSTANCE2 for all the newly generated code */
public static JAXBEqualsStrategy INSTANCE2 = new JAXBEqualsStrategy();
/* Preserve the INSTANCE variable returning EqualsStrategy for backwards compatibility. Simply assign INSTANCE2 to INSTANCE. */
public static EqualsStrategy INSTANCE = INSTANCE2;
```

or

```
public static EqualsStrategy INSTANCE = new JAXBEqualsStrategy();

/* Use a method to access the instance. The JVM JIT compiler will likely inline this call */
public static JAXBEqualsStrategy getInstance() {
    return (JAXBEqualsStrategy) this.INSTANCE;
}
```

There are a number of other possible ways you could accomplish this same objective. I just ask that you consider the "installed user base" of software which has been built against previous releases of the runtime and would benefit from having a smooth upgrade experience.

**Comment by highsource** [comment]
Well, it's definitely not my intention to break the "smooth upgrade experience", I care a lot about compatibility. It's just a bit hard to consider all the possible options.

In this case, I was considering 0.11.0 to be not backwards compatible per se. Generated code is somewhat different from 0.10.x, there was a number of critical fixes as well. So I was actually thinking that you'll have to regenerate code with 0.11.x anyway. A mixed pre-0.11.x/0.11.x setup is not exactly what I had in mind. :)

Nevertheless your suggestion makes sense, I think it can be fixed this way. This will probably mean that existing 0.11.x users will have to regenerate their code now (as their code already uses `ÌNSTANCE`, not `INSTANCE2`). Bu I think it is a good approach. Still have two evil here.

**Comment by highsource** [comment]
This should be fixed in 0.11.2-SNAPSHOT (will be released as 0.12.0). I've opted to `INSTANCE2`/`INSTANCE` approach:

```
	public static DefaultEqualsStrategy INSTANCE2 = new DefaultEqualsStrategy();
	@SuppressWarnings("deprecation")
	public static EqualsStrategy INSTANCE = INSTANCE2;
```

**Comment by highsource** [comment]
Please give it a try and let me know if it works for you.

**Comment by lhanson** [comment]
The fix in the snapshot works for me, old and new code coexists without a problem.

**Comment by highsource** [comment]
I believe this is fixed.
