### ISSUE TITLE
Is there any way to generate short class names from toString? 

### ISSUE THREAD

**Issue by jama707** [highsource/jaxb2-basics#76]
Hello,
The plugin is working fine but am not able to find a way to configure ToString Style (like apache-commons `ToStringBuilder`) or is there any documentation on it?

Thanks!

**Comment by jama707** [comment]
Never mind... I was able to create it by extending `DefaultToStringStrategy`
Posting the code in case some also needs it:

`public class SimpleToStringStrategy extends DefaultToStringStrategy {

    @Override
    public boolean isUseIdentityHashCode() {
        return false;
    }

    @Override
    protected void appendClassName(StringBuilder buffer, Object object) {
        if (object != null) {
            buffer.append(getShortClassName(object.getClass()));
        }
    }
}`

**Comment by highsource** [comment]
Yes, strategy is the way to go. You can also configure it to be the default strategy when generating code.
