### ISSUE TITLE
Add a SimpleToString option 

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb2-basics#82]
The goal would be to have a deep (as possible), reflection-free, runtime-free option similar to the SimpleEquals and SimpleHashcode for toString method creation.

**Comment by ja6a** [comment]
+1

**Comment by andrei-ivanov** [comment]
I see there is a `SimpleToStringPlugin`, but it was disabled by the author at some point.
@highsource Can it be enabled again please? Or is it somehow broken?

**Comment by highsource** [comment]
@andrei-ivanov There's nothing to enable, it was never implemented. The class is a copy-paste of `ToStringPlugin`.

The problem with simple `toString` plugin is that it is very cumbersome to implement it in a non-strategic way. Basically I'd have to generate all the "to string" code contained in the strategies into the schema-derived classes. And "to string" strategies are ca. 3-4x larger than, say, the hash code strategy.

At the same time I don't quite understand what is the problem with an additional runtime dependency. I mean, OK, it is better without the runtime dep, but for the price of ugly code in the `toString` method? I really don't know.

**Comment by mattrpav** [comment]
I was thinking the deep-as-possible is probably the wrong approach.  A shallow inspection of only immediate member primitive and boxes primitives fields would cover a large number of use cases and allow for a depedency-free model jar. Scenarios that need more than first-level could then opt for the toString strategy and the runtime dependency. 

Ie only “to string” member fields of these types:

String 
int / Integer
short / Short
long / Long
double / double
float / Float
boolean / Boolean
etc

**Comment by highsource** [comment]
@mattrpav This would be much easier but to be honest this is very limited. Would not even cover collections or `JAXBElement<T>`.

But I'll think about it.

**Comment by mattrpav** [comment]
@highsource gotcha. Perhaps, for collections it could be a:

`collections != null ? collections.size() : "null"`

I'm fine w/ no support for JAXBElement<T>. I think the idea is to have an option for a bunch of easy use cases to dodge the runtime requirement, but understand that there are corner cases that cause it to jump to the full ToStringStrategy. I could see us using both. We leverege extending the ToStringStrategy to do password and other secret masking, I wouldn't expect that type of functionality in a SimpleString solution.

**Comment by laurentschoelens** [comment]
Closing in favor of follow up issue in jaxb-tools
