### ISSUE TITLE
DefaultToStringStrategy does not allow any configuration.

### ISSUE THREAD

**Issue by ksiczek** [highsource/jaxb2-basics#84]
Hi,

I use it _toString_ method as a kind of a key in grouping some performance results (e.g. each call for the same data should go to the same group) and I need to get rid of the '@' with the object identifier. Is there any way to configure toString strategy to disable 'useIdentityHashCode'?

Thanks in advance,
Karol.

**Comment by highsource** [comment]
You can implement and configure your own strategy. You can't configure existing strategies.
