### ISSUE TITLE
How do I programatically use the plugin without Maven or ANT?

### ISSUE THREAD

**Issue by pathikrit** [highsource/jaxb2-basics#87]
Is there a way to use WsImport + plugins from vanilla Java code (i.e. without any Maven or ANT). The reason I am asking is that I am using this from Scala and would like to use the plugin.

See: https://stackoverflow.com/questions/46550756/programmatically-use-wsimport-with-jaxb-plugins-without-maven-or-ant

    import com.sun.tools.ws.WsImport
   
    def run(wsdlFile: File, destination: File, packageName: String = "generated"): Seq[File] = {        
      sys.props("javax.xml.accessExternalDTD") = "all"
      sys.props("javax.xml.accessExternalSchema") = "all"
      val xjcArgs = ""
      val args = s"-Xnocompile -XadditionalHeaders $xjcArgs -J-Djavax.xml.accessExternalDTD=all -b http://www.w3.org/2001/XMLSchema.xsd -p $packageName -s $destination $wsdlFile".split(' ')
      WsImport.doMain(args)
    }

The above code works and I can generate a Java WSDL client programatically from above Scala code. 

But, now, I also want to use some WsImport plugins (such as [this](https://stackoverflow.com/questions/6523497/how-to-generate-equals-and-hashcode-methods-using-wsimport-in-jaxws) and [this](https://stackoverflow.com/questions/11140317/how-do-i-make-wsimport-generate-constructors)):

    val xjcArgs = "-B-Xequals -B-XhashCode -B-Xvalue-constructor"

I am getting this error: `no such JAXB option: -Xequals` even though I added the following to my classpath:

    "org.jvnet.jaxb2_commons" % "jaxb2-basics" % "1.11.1",
    "org.jvnet.jaxb2_commons" % "jaxb2-value-constructor" % "3.0",

How do I force WsImport to use these plugins? Or do I use some other tool besides the WsImport directly?

**Comment by highsource** [comment]
* Include the plugin with all the required dependencies into the classpath.
* Turn on the desired XJC plugins using CLI arguments like `-XhashCode` et.c
