### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by aznan2** [highsource/jaxb2-basics#91]
With the release of a Java 9 compatible version of maven-jaxb2-plugin rapidly approaching (knock on wood), it would be nice if jaxb2-basics were to follow suit.

At the moment, when i run the java-9 branch of maven-jaxb2-plugin with this config:

    <args>
      <arg>-XsimpleEquals</arg>
      <arg>-XsimpleHashCode</arg>
    </args>
    <plugins>
      <plugin>
        <groupId>org.jvnet.jaxb2_commons</groupId>
        <artifactId>jaxb2-basics</artifactId>
        <version>0.11.2-SNAPSHOT</version>
      </plugin>
    </plugins>

I get `[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb23-plugin:0.13.3-SNAPSHOT:generate (default) on project java9-test-jaxb: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb23-plugin:0.13.3-SNAPSHOT:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb23-plugin:0.13.3-SNAPSHOT:generate: com/sun/tools/xjc/model/Aspect`

**Comment by popshi** [comment]
I have the same issue in Java 10. 

[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate (default) on project msran-jcat-extension-helpers: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1

**Comment by aznan2** [comment]
@highsource I can confirm that it works. Thanks!

**Comment by highsource** [comment]
Great, thanks for the confirmation.
